# Generated by Django 3.2.7 on 2021-09-29 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('category', models.CharField(max_length=60, verbose_name='Category')),
                ('imageURL', models.URLField(verbose_name='Image URL')),
                ('itemURL', models.URLField(verbose_name='Item URL')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('listId', models.AutoField(primary_key=True, serialize=False)),
                ('listName', models.CharField(max_length=60, verbose_name='List Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('username', models.CharField(max_length=60, verbose_name='Username')),
                ('password', models.CharField(max_length=60, verbose_name='Password')),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishlistapp.user'),
        ),
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishlistapp.list'),
        ),
    ]
