# Generated by Django 3.2.7 on 2021-09-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('username', models.CharField(max_length=60, verbose_name='Username')),
                ('password', models.CharField(max_length=60, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('listId', models.AutoField(primary_key=True, serialize=False)),
                ('listName', models.CharField(max_length=60, verbose_name='List Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('category', models.CharField(max_length=60, verbose_name='Category')),
                ('imageURL', models.URLField(verbose_name='Image URL')),
                ('itemURL', models.URLField(verbose_name='Item URL')),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbapp.list')),
            ],
        ),
    ]
